### PR TITLE
Fixes scaling up problem

### LINKED ISSUE #107: Scaling up stops working when max_nodes is reached
If the cluster already has the max number of nodes with some tainted nodes, when the scale-up threshold is reached nothing will happen. No node will be untainted and of course, no node will be added to the cloud provider as well.
This bug also causes another problem. If you have tainted nodes and need to scale up, the max number of nodes that will be untainted at a time will be the difference between the max_nodes and the current number of nodes.
E.g: Nodes = 9
Max number = 10
Tainted = 5
Need more 3 nodes? Instead of untainting 3 nodes at once, only 1 node will be untainted each time scaling up is ran.

Another example from a log:
`time="2018-06-13T18:23:36Z" level=debug msg="**********[AUTOSCALER MAIN LOOP]**********"
time="2018-06-13T18:23:37Z" level=debug msg="**********[START NODEGROUP default]**********"
time="2018-06-13T18:23:37Z" level=info msg="pods total: 48" nodegroup=default
time="2018-06-13T18:23:37Z" level=info msg="nodes remaining total: 18" nodegroup=default
time="2018-06-13T18:23:37Z" level=info msg="cordoned nodes remaining total: 0" nodegroup=default
time="2018-06-13T18:23:37Z" level=info msg="nodes remaining untainted: 12" nodegroup=default
time="2018-06-13T18:23:37Z" level=info msg="nodes remaining tainted: 6" nodegroup=default
time="2018-06-13T18:23:37Z" level=info msg="cpu: 110.43333333333334, memory: 82.31950436831336" nodegroup=default
time="2018-06-13T18:23:37Z" level=debug msg="Unlocking scale lock"
time="2018-06-13T18:23:37Z" level=debug msg="Delta: 5" nodegroup=default
time="2018-06-13T18:23:37Z" level=info msg="increasing nodes exceeds maximum (18). Clamping add amount to (0)"
time="2018-06-13T18:23:37Z" level=warning msg="Scale up delta is less than or equal to 0 after clamping: 0"
time="2018-06-13T18:23:37Z" level=debug msg="DeltaScaled: 0" nodegroup=default
time="2018-06-13T18:23:37Z" level=debug msg="Scaling took a total of 110.042288ms"`

### PR DESCRIPTION
**Pull request by leogdiniz**
Fixes #107

### CODE REVIEW

**Comment by leogdiniz** [comment]
Unfortunately, I have no idea why the job with go:master failed.
With go 1.10.x It didn't fail.
It's my first time doing something with Go so there is a chance that I did something wrong.
Some help would be appreciated. =)

https://travis-ci.org/atlassian/escalator/builds/392085696

**Comment by awprice** [comment]
Thanks for opening this PR @leogdiniz! Could you please sign the CLA in the Contributing section of the readme? https://github.com/atlassian/escalator#contributors

**Comment by leogdiniz** [comment]
Hi @awprice.
I've signed it already.
On my docusign panel it's saying that it was already received by contributions@atlassian.com
Could you check it, please?

**Comment by awprice** [comment]
@leogdiniz Awesome, I'm currently waiting on the team that manages contributions@atlassian.com to confirm with me that they have your signature. I'm also fixing the broken test in #106.

**Comment by awprice** [comment]
@leogdiniz I've updated the tests so it isn't failing now. I'm going to test this over the weekend and will get back to you if there are any changes to be made.

**Comment by awprice** [comment]
Awesome work on this @leogdiniz! 🎉🎉🎉

I've tested this in my cluster and it works perfectly and I can replicat the bug you have described on the current version of Escalator.

Thanks for the contribution!

**Comment by leogdiniz** [comment]
Great news!
This project is awesome.
I'm looking forward to contributing more to it.
I'll just improve my Go skills a little bit more first =)

Cheers

**Pull request merged**
